version: 0.2

phases:
  pre_build:
    commands:
      - echo test prebuild

  build:
    commands:
      - mvn test

  post_build:
    commands:
      - mvn package 


artifacts:
  files:
    - target/SpingBootAws-0.0.1-SNAPSHOT.war