version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto8
      
  pre_build:
    commands:
      - echo test prebuild 1

  build:
    commands:
      - mvn test

  post_build:
    commands:
      - mvn package 


artifacts:
  files:
    - target/SpingBootAws-0.0.1-SNAPSHOT.war